/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.AtualizaDia;
import controle.AtualizadoHora;
import controle.ConnectionConsulta;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloTabela;

/**
 *
 * @author vinicius
 */
public class Lembrete extends javax.swing.JFrame {

    
    ConnectionConsulta conecta = new ConnectionConsulta();
    int xMouse;
    int yMouse;
    
    /**
     * Creates new form Lembrete
     */
    public Lembrete() {
        initComponents();
        
        AtualizadoHora.start(jLabelHorario);  
        AtualizaDia.start(jLabelDia);
       this.setLocation(500,500);

        conecta.conectaBanco();
        preenchertabela("select * from usuarios where destinatario = 'Financeiro' and recebimento = 'Não recebido' order by id");   
        
        
      try {
            conecta.executaSQL("select * from usuarios where destinatario = 'Financeiro' and recebimento = 'Não recebido'");
            conecta.rs.first();
            if(conecta.rs.getString("recebimento").equals("recebido")){
             System.exit(0);
            }else{
          //   JOptionPane.showMessageDialog(rootPane,"Constam malotes para baixa!");
             
            }
        } catch (SQLException ex) {
           // JOptionPane.showMessageDialog(rootPane,"Não existem malotes para baixa!");
            System.exit(0);
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAltera = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAviso = new javax.swing.JTable();
        jComboBoxRec = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBaixa = new javax.swing.JTextField();
        jTextFieldCod = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonReceberTodos = new javax.swing.JButton();
        jLabelDia = new javax.swing.JLabel();
        jLabelHorario = new javax.swing.JLabel();
        jTextFieldDest = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jButtonAltera.setText("Receber");
        jButtonAltera.setEnabled(false);
        jButtonAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlteraActionPerformed(evt);
            }
        });

        jTableAviso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAviso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAvisoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAviso);

        jComboBoxRec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não recebido", "Recebido" }));
        jComboBoxRec.setEnabled(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/und1.jpg"))); // NOI18N
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/und1.jpg"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jTextFieldBaixa.setEditable(false);
        jTextFieldBaixa.setEnabled(false);

        jTextFieldCod.setEnabled(false);

        jButton2.setText("atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/close_1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(26, 21));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/closecinza.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/closecinza.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonReceberTodos.setText("Receber todos");
        jButtonReceberTodos.setEnabled(false);
        jButtonReceberTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceberTodosActionPerformed(evt);
            }
        });

        jLabelDia.setText("jLabel1");

        jLabelHorario.setText("jLabel2");

        jTextFieldDest.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDest, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxRec, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAltera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReceberTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAltera)
                    .addComponent(jButtonReceberTodos)
                    .addComponent(jButton2)
                    .addComponent(jLabelDia)
                    .addComponent(jLabelHorario)
                    .addComponent(jTextFieldDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 829, 196);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAvisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAvisoMouseClicked
        // TODO add your handling code here:
        String id = ""+jTableAviso.getValueAt(jTableAviso.getSelectedRow(), 0);
        conecta.conectaBanco();
        conecta.executaSQL("select * from usuarios where id='"+ id +"'"); 
        try {
        conecta.rs.first(); 
        jTextFieldCod.setText(String.valueOf(conecta.rs.getInt("id")));
        jComboBoxRec.setSelectedItem(conecta.rs.getString("recebimento"));  
        jTextFieldDest.setText(conecta.rs.getString("destinatario"));
        jTextFieldBaixa.setText("Marilia");
        jButtonAltera.setEnabled(true);
        jComboBoxRec.setEnabled(false);
        jButtonReceberTodos.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);          
        }
        
    }//GEN-LAST:event_jTableAvisoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.executaSQL("select * from usuarios where destinatario = 'Financeiro' and recebimento = 'Não recebido'");
            conecta.rs.first();
            if(conecta.rs.getString("recebimento").equals("recebido")){
             System.exit(0);
            }else{
              JOptionPane.showMessageDialog(rootPane,"Ainda constam malotes para baixa!");
           
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Baixas Finalizadas!");
            System.exit(0);
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jButtonAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlteraActionPerformed
        // TODO add your handling code here:
         try {
            PreparedStatement pst = conecta.conn.prepareStatement("update usuarios set recebimento='Recebido', baixa=?, diabaixa=?, horariobaixa=? where id=?");                    
           // pst.setString(1, (String) jComboBoxRec.getSelectedItem()); 
            pst.setString(1, jTextFieldBaixa.getText());           
            pst.setString(2, jLabelDia.getText());
            pst.setString(3, jLabelHorario.getText());
            pst.setInt(4,Integer.parseInt(jTextFieldCod.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Baixa efetuada com sucesso");
            preenchertabela("select * from usuarios where destinatario = 'Financeiro' and recebimento = 'Não recebido' order by id");
            jComboBoxRec.setEnabled(false);
            jTextFieldBaixa.setEnabled(false);
            jButtonAltera.setEnabled(false);
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
           }
    }//GEN-LAST:event_jButtonAlteraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        preenchertabela("select * from usuarios where destinatario = 'Financeiro' and recebimento = 'Não recebido' order by id");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonReceberTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceberTodosActionPerformed
         
         try {
       conecta.conectaBanco();
       PreparedStatement pst = conecta.conn.prepareStatement("update usuarios set recebimento='Recebido', baixa=?, diabaixa=?, horariobaixa=? where recebimento='Não recebido' and destinatario =?");
            
            pst.setString(1,jTextFieldBaixa.getText());
            pst.setString(2, jLabelDia.getText());
            pst.setString(3, jLabelHorario.getText());
            pst.setString(4,jTextFieldDest.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            preenchertabela("select * from usuarios where destinatario = 'Financeiro' and recebimento = 'Não recebido' order by id");
            
            jTextFieldCod.setText("");
            jComboBoxRec.setSelectedItem("");
            jComboBoxRec.setEnabled(false);
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
            
           }
    }//GEN-LAST:event_jButtonReceberTodosActionPerformed

    public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","EMPRESA","DESCRICAO","DEST","DATA","ENTREGA","RECEBIMENTO"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first(); 
        do{
          dados.add(new Object[]{conecta.rs.getInt("id"),conecta.rs.getString("empresa"),conecta.rs.getString("descricao"),conecta.rs.getString("destinatario"),conecta.rs.getString("data"),conecta.rs.getString("entrega"),conecta.rs.getString("recebimento")});
        }while(conecta.rs.next());
        } catch (SQLException ex) {
            
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableAviso.setModel(modelo);
        jTableAviso.getColumnModel().getColumn(0).setPreferredWidth(48);
        jTableAviso.getColumnModel().getColumn(0).setResizable(false);
        jTableAviso.getColumnModel().getColumn(1).setPreferredWidth(155);
        jTableAviso.getColumnModel().getColumn(1).setResizable(false);
        jTableAviso.getColumnModel().getColumn(2).setPreferredWidth(210);
        jTableAviso.getColumnModel().getColumn(2).setResizable(false);
        jTableAviso.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTableAviso.getColumnModel().getColumn(3).setResizable(false);
        jTableAviso.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableAviso.getColumnModel().getColumn(4).setResizable(false);
        jTableAviso.getColumnModel().getColumn(5).setPreferredWidth(68);
        jTableAviso.getColumnModel().getColumn(5).setResizable(false);
        jTableAviso.getColumnModel().getColumn(6).setPreferredWidth(98);
        jTableAviso.getColumnModel().getColumn(6).setResizable(false);
        jTableAviso.getTableHeader().setReorderingAllowed(false);
        jTableAviso.setAutoResizeMode(jTableAviso.AUTO_RESIZE_OFF);
        jTableAviso.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
   
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lembrete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAltera;
    private javax.swing.JButton jButtonReceberTodos;
    private javax.swing.JComboBox<String> jComboBoxRec;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAviso;
    private javax.swing.JTextField jTextFieldBaixa;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldDest;
    // End of variables declaration//GEN-END:variables
}
